name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Docker Setup Compose
        uses: docker/setup-compose-action@v1.2.0
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        run: |
          docker compose --project-directory 3.13 --env_file base.env build --no-cache --provenance true --sbom true --push
          docker compose --project-directory 3.12 --env_file base.env build --no-cache --provenance true --sbom true --push
          docker compose --project-directory 3.11 --env_file base.env build --no-cache --provenance true --sbom true --push
          docker compose --project-directory 3.10 --env_file base.env build --no-cache --provenance true --sbom true --push
